package com.dsharnessmobile.shell

import android.content.Context
import android.media.MediaScannerConnection
import android.os.Environment
import android.util.Log
import java.io.File
import java.io.InputStream
import java.nio.file.Files
import org.apache.commons.compress.archivers.tar.TarArchiveEntry
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream
import org.apache.commons.compress.compressors.xz.XZCompressorInputStream

/**
 * Owns the embedded Termux environment snapshot: first-launch extraction into
 * filesDir/usr and the dsh engine process lifecycle (PATH/LD_LIBRARY_PATH/HOME
 * injected explicitly — the snapshot is self-sufficient, no Termux app needed).
 */
class EngineManager(private val context: Context, private val pickToken: String? = null) {

  val usrDir = File(context.filesDir, "usr")
  val homeDir = File(context.filesDir, "home")

  /** 自包含 proot 落地目录（Operit app 域定制 proot/loader，替换 Termux proot 依赖，坑 38）。 */
  val operitNativeDir = File(usrDir, "share/operit-native")

  /**
   * Public export repo: /storage/emulated/0/Documents/dshdata.
   * Holds only user-initiated session zip exports (exports/) plus a .nomedia anti-scan marker;
   * all runtime user data lives back in private app data (files/home/.dsh).
   */
  val dshDataDir: File
    get() {
      val publicDocs = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS)
        ?: File(context.filesDir, "dshdata-fallback")
      return File(publicDocs, "dshdata")
    }
  private val nodeBin = File(usrDir, "bin/node")
  private val dshBin = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/lib/bin.js")

  /** Consecutive healthy probe ticks since the last update swap (update-v2 confirmation state). */
  private var updateHealthTicks = 0

  val engineReady: Boolean get() = nodeBin.exists()

  /**
   * Deploy the undo emergency CLI (assets/undo-emergency.mjs → filesDir).
   * Idempotent: content equals the asset → skip. Missing node still succeeds
   * (the file itself is versioned with the app); UndoGate checks child exit code.
   */
  fun deployUndoCli() {
    try {
      val asset = "undo-emergency.mjs"
      if (context.assets.open(asset).use { it.readBytes() }.let { b ->
          File(context.filesDir, asset).takeIf { it.exists() }?.readBytes()?.contentEquals(b) != true
        }) {
        context.assets.open(asset).use { input ->
          File(context.filesDir, asset).outputStream().use { input.copyTo(it) }
        }
        Log.i(TAG, "undo emergency CLI deployed")
      }
    } catch (t: Throwable) {
      Log.e(TAG, "undo CLI deploy failed (non-fatal): " + t.message)
    }
  }

  /** Embedded snapshot fingerprint (assets/snapshot.sha256, generated by build-release.ps1). */
  private fun bundledFingerprint(): String = try {
    context.assets.open("snapshot.sha256").bufferedReader().use { it.readText().trim() }
  } catch (_: Exception) {
    ""
  }

  private fun fingerprintFile(): File = File(context.filesDir, ".snapshot-fingerprint")

  /**
   * Whether the snapshot is extracted and matches the embedded version: node exists + fingerprint match.
   * Upgrade lesson (v0.10.5→v0.10.6): engineReady only checked node existence, so an upgrade never
   * re-extracted → old plugins kept running (injection-guard fixes etc. never took effect).
   */
  fun snapshotFresh(): Boolean {
    if (!nodeBin.exists()) return false
    val fp = bundledFingerprint()
    if (fp.isEmpty()) return true // no fingerprint file (legacy build): don't force a re-extract
    return fingerprintFile().exists() && fingerprintFile().readText().trim() == fp
  }

  /**
   * Upgrade/snapshot change: back up user data → fully re-extract the embedded snapshot → restore user
   * data → write the fingerprint. The snapshot strips sessions/storages/attachments/credentials/settings
   * (see make-snapshot.sh), so a plain re-extract would "lose" that private data — backup first, restore
   * after; factory profiles (cordis*.yml/node_modules) follow the snapshot (manual patches must be
   * re-applied on top of the new baseline). On any failure: restore the backup and keep the old runtime
   * (retried on next start).
   */
  fun refreshSnapshot(onProgress: (Long, Long) -> Unit): Boolean {
    val backup = File(context.filesDir, ".dsh-backup")
    val dsh = File(homeDir, ".dsh")
    try {
      if (dsh.exists()) {
        backup.deleteRecursively()
        // Upgrade-residue tolerance (v0.12.4): profile node_modules may carry dangling symlinks
        // pointing at packages that no longer exist (npm layout changes) — copyRecursively's
        // exists() check on a dangling link throws NoSuchFileException and fails the whole refresh.
        // Drop broken links before backing up (profiles follow the snapshot; the backup omits them).
        dsh.walkTopDown().forEach { if (java.nio.file.Files.isSymbolicLink(it.toPath()) && !it.exists()) it.delete() }
        dsh.copyRecursively(backup)
      }
      val ok = extractSnapshot(onProgress)
      if (!ok) {
        restoreUserData(backup, dsh)
        Log.e(TAG, "snapshot refresh: extract failed, kept old runtime")
        return false
      }
      extractToolAssets() // 内置工具/ubuntu rootfs 解压（非致命，失败仅记录）
      restoreUserData(backup, dsh)
      backup.deleteRecursively()
      fingerprintFile().writeText(bundledFingerprint())
      Log.i(TAG, "snapshot refreshed (fingerprint " + bundledFingerprint().take(12) + ")")
      return true
    } catch (t: Throwable) {
      restoreUserData(backup, dsh)
      Log.e(TAG, "snapshot refresh failed; kept old runtime", t)
      return false
    }
  }

  /** Restore the snapshot-stripped user data dirs/files (copied back from the backup into private .dsh).
   *  Never throws (Review 2026-08-18 R2): refreshSnapshot's failure branch calls this on a background
   *  thread, so a restore failure must not escape — otherwise the exception kills the thread and the UI
   *  hangs on "Updating runtime…" with no message. Failures only log; the backup is kept for a retry. */
  private fun restoreUserData(backup: File, dsh: File) {
    if (!backup.exists()) return
    for (name in listOf(
      "sessions", "storages", "attachments",
      ".credentials.yaml", "settings.yaml", ".anonymous-user-id", ".private-layout",
    )) {
      try {
        val src = File(backup, name)
        if (!src.exists()) continue
        val dst = File(dsh, name)
        if (dst.exists()) dst.deleteRecursively()
        src.copyRecursively(dst)
      } catch (t: Throwable) {
        Log.e(TAG, "restore user data failed for $name; backup kept at " + backup.absolutePath, t)
      }
    }
  }

  /** Process-level start guard (MainActivity and EngineService each construct their own EngineManager;
   *  instance fields are invisible across them — the double-start race needs companion-level CAS). */
  private val starting: Boolean
    get() = STARTING.get()

  /**
   * Extract the bundled snapshot archive into filesDir. Runs on any thread;
   * callers own the progress UI.
   * @param onProgress bytesDone, bytesTotal.
   * @returns true on success.
   */
  fun extractSnapshot(onProgress: (Long, Long) -> Unit): Boolean {
    return try {
      val fd = context.assets.openFd("snapshot.tar.xz")
      SnapshotExtractor.extract(context.assets.open("snapshot.tar.xz"), fd.length, usrDir.parentFile, onProgress)
      homeDir.mkdirs()
      true
    } catch (t: Throwable) {
      Log.e(TAG, "snapshot extract failed", t)
      false
    }
  }

  /**
   * Extract Seagull built-in developer tools from APK assets into the runtime.
   *
   * Layout mirrors tool-installer's registry install paths:
   *   assets/tools/apktool.jar       -> files/usr/share/apktool/apktool.jar
   *   assets/native/liboperit_*.so   -> files/usr/share/operit-native/{proot,loader}
   *   assets/ubuntu-rootfs.tar.xz    -> files/home/.dsh/ubuntu-rootfs/
   *                                    + proot-entry.sh (plugin entry point)
   *
   * 轻资产化（2026-09-18 P2）：jadx/radare2/rizin 不再随包解压，改 tool-installer 在线安装。
   * 防坏（P1）：见 extractToolAssetsLocked 的 manifest 核验 + staging + stamp 路径。
   *
   * Optional: a missing asset is skipped; a failure logs and does not block
   * engine startup. Runs after snapshot extraction (first launch + refresh).
   */
  fun extractToolAssets(): Boolean {
    // 并发锁（companion 级）：MainActivity 与 EngineService 各持一个 EngineManager 实例，
    // 启动流程可能并发进入 startEngine → 并发重解压同一批资产 → symlink 撞车
    // （真机实测 FileAlreadyExistsException）。单飞：谁先拿到锁谁解，后到者复用结果。
    synchronized(TOOL_EXTRACT_LOCK) {
      return extractToolAssetsLocked()
    }
  }

  private fun extractToolAssetsLocked(): Boolean {
    // 防坏重构（2026-09-18，对齐 DSHA「构建期锁哈希 + 落地后核验 + 原子写」范式）：
    // 旧实现以「5 个文件 exists()」判完成——解压中断/半份落地后永久定格为成功（工具装好即坏
    // 的根因）。新实现：全部落到 staging 目录 → asset-manifest.json 逐项核验 → 原子 rename
    // 进位 → 成功才写 stamp。stamp = 清单哈希 + 资产哈希 + APK identity（path:len:mtime，
    // 覆盖安装必变）。任何一步失败 → 清 staging、不写 stamp → 下次启动重解，绝不半份定格。
    val manifest = loadAssetManifest()
    if (manifest == null) {
      // 清单缺失 = 未经 build-apk.mjs 的裸构建（本地直跑 gradle）：保持旧式 exists 判定，
      // 不阻塞开发迭代；CI/正式包永远有清单（gen-asset-manifest 在 gradle 前强制生成）。
      return extractToolAssetsLegacy()
    }
    if (!hasAsset("tools/apktool.jar") && !hasAsset("native/liboperit_proot.so") &&
        !hasAsset("native/liboperit_loader.so") && !hasAsset("ubuntu-rootfs.tar.xz")) {
      // APK 不含任何工具资产（协调库本地构建形态）：无事可做直接成功——若继续走
      // staging 流程，锚点核验会对着「永远不可能在场」的落点失败 → 每启动重解不收敛。
      return true
    }
    // 幂等锚点必须「按资产在场」推导：清单在但个别资产缺（协调库本地构建只少 rootfs 等）时，
    // 硬编码全量锚点会永不满足 → stamp 匹配也每启动重解（永不收敛的重解风暴）。
    val stampFile = File(context.filesDir, ".toolassets-stamp")
    val stamp = toolAssetsStamp(manifest)
    val anchors = ArrayList<File>()
    if (hasAsset("tools/apktool.jar")) anchors.add(File(usrDir, "share/apktool/apktool.jar"))
    if (hasAsset("native/liboperit_proot.so")) anchors.add(File(operitNativeDir, "proot"))
    if (hasAsset("native/liboperit_loader.so")) anchors.add(File(operitNativeDir, "loader"))
    if (hasAsset("ubuntu-rootfs.tar.xz")) {
      anchors.add(File(homeDir, ".dsh/ubuntu-rootfs/proot-entry.sh"))
      anchors.add(File(homeDir, ".dsh/ubuntu-rootfs/bin/bash"))
    }
    if (stampFile.exists() && stampFile.readText().trim() == stamp && anchors.all { it.exists() }) {
      return true
    }
    val staging = File(context.filesDir, ".toolassets-staging")
    return try {
      staging.deleteRecursively()
      staging.mkdirs()
      val stUsr = File(staging, "usr")
      val stHome = File(staging, "home")
      val stNative = File(stUsr, "share/operit-native")
      val stRootfs = File(stHome, ".dsh/ubuntu-rootfs")
      // 1) staging 落地（旧实现中 radare2/rizin/jadx 已改在线安装，不再随包解压）。
      copyAssetToStaged("tools/apktool.jar", File(stUsr, "share/apktool/apktool.jar"))
      copyAssetToStaged("native/liboperit_proot.so", File(stNative, "proot")).setExecutable(true, false)
      copyAssetToStaged("native/liboperit_loader.so", File(stNative, "loader")).setExecutable(true, false)
      extractTarAsset("ubuntu-rootfs.tar.xz", stRootfs, "xz", stripTopDir = true)
      writeProotEntry(File(stRootfs, "proot-entry.sh"))
      // 2) 核验：资产本体哈希（逐字节 copy 项）+ rootfs 抽检成员/统计（防解一半）。
      verifyAssetHashes(manifest, staging)
      verifyRootfs(manifest, stRootfs)
      // 3) 进位：逐路径递归合并（staging 树 → usr/home，引擎树与用户数据分毫不动）。
      promoteTree(stUsr, usrDir)
      promoteTree(stHome, homeDir)
      staging.deleteRecursively()
      // 4) 成功才盖章——失败/中断的路径永远不写 stamp。
      stampFile.writeText(stamp + "\n")
      Log.i(TAG, "tool assets extracted & verified (stamp " + stamp.take(12) + ")")
      true
    } catch (t: Throwable) {
      Log.e(TAG, "tool asset extract failed (non-fatal; staging discarded, retry next start)", t)
      try { staging.deleteRecursively() } catch (_: Throwable) {}
      false
    }
  }

  /** 旧式无清单路径（本地裸构建/开发包）：保持 exists 判定语义，不做核验。 */
  private fun extractToolAssetsLegacy(): Boolean {
    val apkJar = File(usrDir, "share/apktool/apktool.jar")
    val prootEntry = File(homeDir, ".dsh/ubuntu-rootfs/proot-entry.sh")
    val rootfsBash = File(homeDir, ".dsh/ubuntu-rootfs/bin/bash")
    val operitProot = File(operitNativeDir, "proot")
    val operitLoader = File(operitNativeDir, "loader")
    if (apkJar.exists() && prootEntry.exists() && rootfsBash.exists() &&
        operitProot.exists() && operitLoader.exists()) {
      return true
    }
    return try {
      copyAssetToFile("tools/apktool.jar", apkJar)
      copyAssetToFile("native/liboperit_proot.so", operitProot)
      copyAssetToFile("native/liboperit_loader.so", operitLoader)
      operitProot.setExecutable(true, false)
      operitLoader.setExecutable(true, false)
      extractTarAsset("ubuntu-rootfs.tar.xz", File(homeDir, ".dsh/ubuntu-rootfs"), "xz", stripTopDir = true)
      writeProotEntry(prootEntry)
      Log.i(TAG, "tool assets extracted (legacy, no manifest)")
      true
    } catch (t: Throwable) {
      Log.e(TAG, "tool asset extract failed (non-fatal)", t)
      false
    }
  }

  /** asset-manifest.json（build-apk.mjs 打包前由 gen-asset-manifest.mjs 生成）。 */
  private class AssetManifest(
    val sha256: String,
    val assets: Map<String, String>,
    val probes: Map<String, String>,
    val rootfsMembers: Int,
    val rootfsFileBytes: Long,
  )

  private fun loadAssetManifest(): AssetManifest? = try {
    val text = context.assets.open("asset-manifest.json").bufferedReader().use { it.readText() }
    val json = org.json.JSONObject(text)
    val assets = LinkedHashMap<String, String>()
    val a = json.getJSONObject("assets")
    for (k in a.keys()) assets[k] = a.getString(k)
    val probes = LinkedHashMap<String, String>()
    val p = json.getJSONObject("probes")
    for (k in p.keys()) probes[k] = p.getString(k)
    val stats = json.getJSONObject("rootfsStats").optJSONObject("ubuntu-rootfs.tar.xz")
    AssetManifest(
      sha256 = sha256Of(text.toByteArray(Charsets.UTF_8)),
      assets = assets,
      probes = probes,
      rootfsMembers = stats?.optInt("members", -1) ?: -1,
      rootfsFileBytes = stats?.optLong("fileBytes", -1L) ?: -1L,
    )
  } catch (_: Throwable) {
    null
  }

  /** stamp = 清单哈希 + 资产本体哈希聚合 + APK identity。path:len:mtime 换包必变（DSHA 同款）。 */
  private fun toolAssetsStamp(m: AssetManifest): String {
    val agg = createHash()
    agg.update(m.sha256.toByteArray(Charsets.UTF_8))
    m.assets.toSortedMap().forEach { (k, v) -> agg.update((k + v).toByteArray(Charsets.UTF_8)) }
    val apk = File(context.applicationInfo.sourceDir)
    val identity = apk.path + ":" + apk.length() + ":" + apk.lastModified()
    agg.update(identity.toByteArray(Charsets.UTF_8))
    return hexOf(agg.digest())
  }

  /** 核验 staging 内逐字节 copy 的资产本体哈希。清单有项 = 打包时资产必在场 → 落点缺失/篡改都必须抛：
   *  若放过缺失项，stamp 照写但幂等锚点检查永远失败 → 每次启动全量重解（永不收敛的重解风暴）。 */
  private fun verifyAssetHashes(m: AssetManifest, staging: File) {
    for ((asset, expected) in m.assets) {
      val dest = when {
        asset == "tools/apktool.jar" -> File(staging, "usr/share/apktool/apktool.jar")
        asset == "native/liboperit_proot.so" -> File(staging, "usr/share/operit-native/proot")
        asset == "native/liboperit_loader.so" -> File(staging, "usr/share/operit-native/loader")
        else -> continue // 在线装类（jadx/r2/rizin 旧清单可能仍有项）无逐字节落点
      }
      if (!dest.exists()) throw java.io.IOException("asset missing after extract: " + asset)
      if (sha256File(dest) != expected) {
        throw java.io.IOException("asset hash mismatch: " + asset)
      }
    }
  }

  /** rootfs 落点核验：成员数/文件字节对账 + 抽检成员哈希（软链成员=链接目标串哈希）。 */
  private fun verifyRootfs(m: AssetManifest, rootfsDir: File) {
    if (m.rootfsMembers < 0 && m.probes.isEmpty()) return // 清单无 rootfs 数据（轻资产外构建）
    var files = 0L
    var bytes = 0L
    rootfsDir.walkTopDown().forEach { f ->
      if (f == rootfsDir) return@forEach
      files++
      if (f.isFile && !java.nio.file.Files.isSymbolicLink(f.toPath())) bytes += f.length()
    }
    // 成员数与字节均为「不足即失败」下界判定：解一半时数量级差距 << 清单；壳侧额外落地
    // （proot-entry.sh + fake-sysdata 共 5 个常规文件）只会抬高计数，故不能用相等判定。
    if (m.rootfsMembers in 0..Int.MAX_VALUE && files < m.rootfsMembers) {
      throw java.io.IOException("rootfs incomplete: entries " + files + " < manifest " + m.rootfsMembers)
    }
    if (m.rootfsFileBytes > 0 && bytes < m.rootfsFileBytes) {
      throw java.io.IOException("rootfs bytes incomplete: " + bytes + " < manifest " + m.rootfsFileBytes)
    }
    for ((path, expected) in m.probes) {
      val f = File(rootfsDir, path)
      if (!f.exists()) throw java.io.IOException("rootfs probe missing: " + path)
      val got = if (java.nio.file.Files.isSymbolicLink(f.toPath())) {
        sha256Of(java.nio.file.Files.readSymbolicLink(f.toPath()).toString().toByteArray(Charsets.UTF_8))
      } else {
        sha256File(f)
      }
      if (got != expected) throw java.io.IOException("rootfs probe hash mismatch: " + path)
    }
  }

  /**
   * 进位：把 staging 子树合并进目标树。**逐路径递归**——只替换 staging 里真实存在的落点，
   * 绝不整目录顶替（usr/share、home/.dsh 下有快照引擎树与用户数据，删了就是灾难）。
   * 目录：双方存在 → 递归合并；仅 staging 有 → rename（跨卷失败退 verified copy）。
   * 文件/软链：deleteForOverwrite 旧落点 → rename。
   */
  private fun promoteTree(from: File, to: File) {
    to.mkdirs()
    from.listFiles()?.forEach { child ->
      val target = File(to, child.name)
      val childIsDir = child.isDirectory && !java.nio.file.Files.isSymbolicLink(child.toPath())
      if (childIsDir) {
        if (target.exists() && !target.isDirectory) {
          deleteForOverwrite(target)
          if (!child.renameTo(target)) throw java.io.IOException("promote failed: " + target.absolutePath)
        } else {
          promoteTree(child, target)
          child.delete() // 合并后 staging 空目录收尾（失败无害）
        }
      } else {
        deleteForOverwrite(target)
        if (!child.renameTo(target)) {
          copyTreeVerified(child, target)
          child.delete()
        }
      }
    }
  }

  /** 覆盖写清理（与 SnapshotExtractor 同语义）：软链/文件直删不跟随；非空目录递归删。 */
  private fun deleteForOverwrite(target: File) {
    if (!target.exists() && !java.nio.file.Files.isSymbolicLink(target.toPath())) return
    try {
      if (java.nio.file.Files.isDirectory(target.toPath(), java.nio.file.LinkOption.NOFOLLOW_LINKS)) {
        target.walkBottomUp().forEach { it.delete() }
      } else {
        java.nio.file.Files.deleteIfExists(target.toPath())
      }
    } catch (t: Throwable) {
      Log.w(TAG, "deleteForOverwrite failed: " + target.absolutePath, t)
    }
  }

  /** copy 资产到 staging（原子：写 .part 再 rename；不跟随旧目标）。 */
  private fun copyAssetToStaged(asset: String, dest: File): File {
    if (!hasAsset(asset)) return dest
    dest.parentFile?.mkdirs()
    val staged = File(dest.parentFile, dest.name + ".part")
    context.assets.open(asset).use { input -> staged.outputStream().use { input.copyTo(it) } }
    java.nio.file.Files.deleteIfExists(dest.toPath())
    if (!staged.renameTo(dest)) throw java.io.IOException("staged rename failed: " + dest.absolutePath)
    return dest
  }

  private fun createHash(): java.security.MessageDigest =
    java.security.MessageDigest.getInstance("SHA-256")

  private fun hexOf(bytes: ByteArray): String =
    bytes.joinToString("") { String.format(java.util.Locale.ROOT, "%02x", it) }

  private fun sha256Of(data: ByteArray): String = hexOf(createHash().digest(data))

  private fun sha256File(f: File): String {
    val d = createHash()
    f.inputStream().use { input ->
      val buf = ByteArray(64 * 1024)
      var n = input.read(buf)
      while (n >= 0) { d.update(buf, 0, n); n = input.read(buf) }
    }
    return hexOf(d.digest())
  }

  /** Copy a single asset (jar etc.) to dest, overwriting, skipping if absent. */
  private fun copyAssetToFile(asset: String, dest: File) {
    if (!hasAsset(asset)) return
    dest.parentFile?.mkdirs()
    java.nio.file.Files.deleteIfExists(dest.toPath())
    context.assets.open(asset).use { input ->
      dest.outputStream().use { out -> input.copyTo(out) }
    }
    Log.i(TAG, "tool asset: $asset -> " + dest.absolutePath)
  }

  /**
   * Extract a tar asset (xz or gzip) into dest.
   * Mirrors SnapshotExtractor safety: handles dir/symlink/regular files, rejects
   * absolute paths and ../ traversal, and only writes inside dest. proot-distro
   * rootfs tarballs are full of `bin -> usr/bin` symlinks — dropping them (as the
   * first version did) breaks /bin,/lib and the container cannot start.
   *
   * @param stripTopDir proot-distro 根文件系统 tar 顶层是单目录（ubuntu-noble-aarch64/），
   *                    剥离后内容直接落在 dest（否则 bin/bash 在子目录，proot 起不来）。
   */
  private fun extractTarAsset(asset: String, dest: File, comp: String, stripTopDir: Boolean = false, stripComponents: Int = 0) {
    if (!hasAsset(asset)) return
    dest.mkdirs()
    val destCanon = dest.canonicalPath
    // 预扫：若启用了 stripTopDir，探测第一个顶层目录名（tar 条目第一段）。
    var topPrefix: String? = null
    if (stripTopDir) {
      context.assets.open(asset).use { input ->
        val s: InputStream =
          if (comp == "gz") org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream(input)
          else XZCompressorInputStream(input)
        val t = TarArchiveInputStream(s)
        var e = t.nextEntry
        while (e != null && topPrefix == null) {
          val first = e.name.replace('\\', '/').trimStart('/').substringBefore('/')
          if (first.isNotEmpty()) topPrefix = first
          e = t.nextEntry
        }
        t.close()
      }
    }
    context.assets.open(asset).use { input ->
      val stream: InputStream =
        if (comp == "gz") org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream(input)
        else XZCompressorInputStream(input)
      val tar = TarArchiveInputStream(stream)
      var entry: TarArchiveEntry? = tar.nextEntry
      while (entry != null) {
        val target = resolveAssetEntry(dest, destCanon, entry, topPrefix, stripComponents)
        if (target != null) {
          when {
            entry.isDirectory -> target.mkdirs()
            entry.isSymbolicLink -> {
              target.parentFile?.mkdirs()
              val linkCanon = File(target.parentFile, entry.linkName).canonicalPath
              if (linkCanon.startsWith(destCanon + File.separator)) {
                java.nio.file.Files.deleteIfExists(target.toPath())
                java.nio.file.Files.createSymbolicLink(
                  target.toPath(), java.nio.file.Paths.get(entry.linkName),
                )
              } else {
                Log.w(TAG, "skip unsafe symlink: " + entry.name + " -> " + entry.linkName)
              }
            }
            else -> {
              target.parentFile?.mkdirs()
              java.nio.file.Files.deleteIfExists(target.toPath())
              target.outputStream().use { out ->
                val buf = ByteArray(64 * 1024)
                var n = tar.read(buf)
                while (n >= 0) { out.write(buf, 0, n); n = tar.read(buf) }
              }
              // preserve exec bit for binaries (harmless if kernel ignores it)
              target.setExecutable(entry.mode and 0x40 != 0, true)
            }
          }
        }
        entry = tar.nextEntry
      }
    }
    Log.i(TAG, "tool asset: $asset -> " + dest.absolutePath)
  }

  /** Resolve a tar entry inside dest, rejecting absolute paths and ../ traversal.
   *  @param topPrefix 非空时剥离该顶层前缀（proot-distro 单目录 rootfs）。 */
  private fun resolveAssetEntry(dest: File, destCanon: String, entry: TarArchiveEntry, topPrefix: String? = null, stripComponents: Int = 0): File? {
    var name = entry.name.replace('\\', '/').trimStart('/')
    if (stripComponents > 0) {
      val parts = name.split('/')
      if (parts.size <= stripComponents) return null
      name = parts.drop(stripComponents).joinToString("/")
    } else if (topPrefix != null && name.startsWith(topPrefix + "/")) {
      name = name.substring(topPrefix.length + 1)
    }
    if (name.isEmpty() || name.contains("..")) return null
    val target = File(dest, name)
    return try {
      val parentCanon = (target.parentFile?.canonicalPath ?: destCanon)
      if (parentCanon.startsWith(destCanon + File.separator) || parentCanon == destCanon) target else null
    } catch (_: Exception) {
      null
    }
  }

  /** Write the proot-entry.sh launcher the dev-tools plugin (ubuntu_exec) invokes. */
  private fun writeProotEntry(entry: File) {
    entry.parentFile?.mkdirs()
    // 对齐 scripts/launch_ubuntu_proot.sh 的伪造 /proc 补丁：Android 内核 /proc/stat
    // 缺桌面字段，容器内 nproc/ps/CMake -j 会读 0 核或解析失败。必须先落伪造文件，
    // 再在 proot 命令行里 bind 到 /proc/{stat,loadavg,uptime,version}。
    writeFakeSysdata(entry.parentFile)
    val prootBin = File(operitNativeDir, "proot").absolutePath
    val loaderBin = File(operitNativeDir, "loader").absolutePath
    val script = """#!/bin/bash
# Seagull DevStudio Ubuntu container entry (rootfs top-level)
# 优先 root chroot（KernelSU/Magisk su 可用时）；无 root 时 fallback proot。
ROOTFS_DIR="${'$'}(cd "${'$'}(dirname "${'$'}{BASH_SOURCE[0]}")" && pwd)"
# 提取命令：兼容 `-lc CMD`（ubuntu_exec 默认）与直接 `CMD...`。
if [ "${'$'}{1:-}" = "-lc" ] || [ "${'$'}{1:-}" = "-c" ]; then CMD="${'$'}{2:-}"; else CMD="${'$'}*"; fi
# ---- Root chroot 路径（su 可用时）----
if [ -x /system/bin/su ]; then
  CMD_B64="${'$'}(printf '%s' "${'$'}CMD" | base64 | tr -d '\n')"
  exec /system/bin/su -c "export PATH=/system/bin:/system/xbin:/system/usr/bin; export LD_LIBRARY_PATH=/system/lib64:/system/lib; export LD_PRELOAD=; R='${'$'}ROOTFS_DIR'; mount -t proc proc \"\${'$'}R/proc\" 2>/dev/null; mount -t sysfs sys \"\${'$'}R/sys\" 2>/dev/null; mount -o bind /dev \"\${'$'}R/dev\" 2>/dev/null; mount -t devpts devpts \"\${'$'}R/dev/pts\" 2>/dev/null; [ -s \"\${'$'}R/etc/resolv.conf\" ] || printf 'nameserver 8.8.8.8\nnameserver 114.114.114.114\n' > \"\${'$'}R/etc/resolv.conf\"; C=\$(printf '%s' '${'$'}CMD_B64' | base64 -d 2>/dev/null); exec chroot \"\${'$'}R\" /usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root TERM=xterm LANG=C.UTF-8 /bin/bash -lc \"\${'$'}C\""
fi
# ---- proot fallback ----
export PROOT_TMP_DIR="${'$'}{TMPDIR:-${'$'}HOME/tmp}"
mkdir -p "${'$'}PROOT_TMP_DIR"
PROOT_BIN="${'$'}{PROOT_BIN:-$prootBin}"
export PROOT_LOADER="${'$'}{PROOT_LOADER:-$loaderBin}"
# 清理 termux-exec 的 execve 拦截（会把 guest 路径改写成宿主 PREFIX 路径，导致 proot execve 失败）。
unset LD_PRELOAD TERMUX_EXEC__EXECVE_CALL__INTERCEPT TERMUX_EXEC__SYSTEM_LINKER_EXEC__MODE TERMUX_EXEC__PROC_SELF_EXE
exec "${'$'}PROOT_BIN" --link2symlink --kill-on-exit -0 -r "${'$'}ROOTFS_DIR" -b /dev -b /proc -b /sys -b /storage -b "${'$'}ROOTFS_DIR/proc/.stat:/proc/stat" -b "${'$'}ROOTFS_DIR/proc/.loadavg:/proc/loadavg" -b "${'$'}ROOTFS_DIR/proc/.uptime:/proc/uptime" -b "${'$'}ROOTFS_DIR/proc/.version:/proc/version" -b "${'$'}{HOME}:${'$'}{HOME}" -w "${'$'}{HOME}" /bin/bash "${'$'}@"
"""
    java.nio.file.Files.deleteIfExists(entry.toPath())
    entry.writeText(script)
    entry.setExecutable(true, false)
    Log.i(TAG, "proot-entry.sh written at " + entry.absolutePath)
  }

  /**
   * 伪造受限 /proc 节点（与 scripts/setup_fake_sysdata.sh 内容一致）。Android 内核的
   * /proc/stat 缺少桌面 Linux 字段，Ubuntu 内 nproc/ps/CMake 等依赖 /proc/stat 的工具会
   * 读到 0 核或解析失败；proot-entry 里 bind 这些伪造文件覆盖容器内 /proc 对应节点。
   */
  private fun writeFakeSysdata(rootfs: File?) {
    if (rootfs == null) return
    val proc = File(rootfs, "proc")
    val sysEmpty = File(rootfs, "sys/.empty")
    proc.mkdirs()
    sysEmpty.mkdirs()
    val stat =
      "cpu  1957 0 2877 93280 262 342 254 87 0 0\n" +
        "cpu0 31 0 226 12027 82 10 4 9 0 0\n" +
        "cpu1 45 0 664 11144 21 263 233 12 0 0\n" +
        "cpu2 494 0 537 11283 27 10 3 8 0 0\n" +
        "cpu3 359 0 234 11723 24 26 5 7 0 0\n" +
        "intr 127541 38 290 0 0 0 0 4 0 1 0 0\n" +
        "ctxt 140223\n" +
        "btime 1680020856\n" +
        "processes 772\n" +
        "procs_running 2\n" +
        "procs_blocked 0\n"
    val fake = mapOf(
      ".loadavg" to "0.12 0.07 0.02 2/165 765\n",
      ".stat" to stat,
      ".uptime" to "3456.78 27654.32\n",
      ".version" to "Linux version 6.1.0-seagull-arm64 (gcc 13.2.0) #1 SMP PREEMPT\n",
    )
    for ((name, content) in fake) {
      val f = File(proc, name)
      if (!f.exists()) f.writeText(content)
    }
  }

  /** Whether an asset exists in the APK (guards optional tools). */
  private fun hasAsset(name: String): Boolean {
    return try {
      val dir = File(name).parent ?: ""
      val names = context.assets.list(dir) ?: return false
      names.contains(File(name).name)
    } catch (t: Throwable) { false }
  }

  /**
   * Ensure the private DSH_HOME data layout is ready (idempotent, called from a background thread).
   *
   * Since v0.10.5 all runtime data lives in private app data; Documents/dshdata stays only as the
   * user-initiated export repo (exports/ + .nomedia). This method:
   *  - on a first/clean install: sets up the private .dsh layout and the public export repo;
   *  - when it detects a pre-v0.10.4 public migration layout (.migrated-from or private symlinks):
   *    performs a reverse migration, copying sessions/storages/attachments/profiles/settings.yaml
   *    back into private storage and cleaning up the public leftovers;
   *  - on any failure keeps the public data; the engine still starts with a private DSH_HOME and
   *    retries next time.
   *
   * DSH_HOME always stays in the private domain: the profiles/node_modules flat-fallback symlink
   * mechanism depends on the app-private domain (public FUSE forbids symlinks), so DSH_HOME must
   * never be migrated wholesale.
   */
  fun ensurePrivateDshData(): File {
    val dshData = dshDataDir
    val privateDsh = File(homeDir, ".dsh")
    privateDsh.mkdirs()
    val privateMarker = File(privateDsh, ".private-layout")
    if (privateMarker.exists()) {
      ensurePublicExportRepo(dshData)
      return privateDsh
    }
    if (isLegacyPublicLayout(dshData, privateDsh)) {
      try {
        reverseMigrate(dshData, privateDsh)
        privateMarker.writeText("private")
        ensurePublicExportRepo(dshData)
        Log.i(TAG, "dshdata reverse migration done -> " + privateDsh.absolutePath)
      } catch (t: Throwable) {
        // A migration failure must not block startup: DSH_HOME stays private, the engine works, retry later.
        Log.e(TAG, "dshdata reverse migration failed; keeping public data", t)
      }
    } else {
      // Clean install or already-private layout: just mark it, no migration needed.
      try {
        privateMarker.writeText("private")
      } catch (t: Throwable) {
        Log.w(TAG, "private layout marker write failed", t)
      }
      ensurePublicExportRepo(dshData)
    }
    return privateDsh
  }

  /** Detect the pre-v0.10.4 public migration layout. */
  private fun isLegacyPublicLayout(dshData: File, privateDsh: File): Boolean {
    if (File(dshData, ".migrated-from").exists()) return true
    for (name in listOf("sessions", "storages", "attachments")) {
      if (isSymlink(File(privateDsh, name))) return true
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        if (isSymlink(File(privateDsh, "profiles/$profile/$name"))) return true
      }
    }
    return false
  }

  /** Reverse migration: copy public data back into private storage, clean up the public leftovers. */
  private fun reverseMigrate(dshData: File, privateDsh: File) {
    for (name in listOf("sessions", "storages", "attachments")) {
      reverseMigrateDir(File(privateDsh, name), File(dshData, name))
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        reverseMigrateFile(
          File(privateDsh, "profiles/$profile/$name"),
          File(dshData, "profiles/$profile/$name"),
        )
      }
    }
    reverseMigrateFile(File(privateDsh, "settings.yaml"), File(dshData, "settings.yaml"))

    // Clean up stale public data (conflicts were renamed *.public-backup, so they're untouched).
    val removedPaths = mutableListOf<String>()
    for (name in listOf("sessions", "storages", "attachments", "profiles", "settings.yaml", ".migrated-from")) {
      val f = File(dshData, name)
      if (f.exists()) {
        removedPaths += f.absolutePath
        if (!f.deleteRecursively()) {
          throw java.io.IOException("failed to delete public path " + f.absolutePath)
        }
      }
    }
    // Tell MediaScanner the old public subdirs are gone, clearing the fake video entries it indexed.
    if (removedPaths.isNotEmpty()) {
      try {
        MediaScannerConnection.scanFile(context, removedPaths.toTypedArray(), null, null)
      } catch (t: Throwable) {
        Log.w(TAG, "media scan cleanup failed", t)
      }
    }
  }

  /** Dir-level reverse migration: drop the private symlink, copy the public entity back with a verified copy, then delete the public source. */
  private fun reverseMigrateDir(privateDir: File, publicDir: File) {
    if (isSymlink(privateDir)) {
      Files.delete(privateDir.toPath())
    }
    if (!publicDir.isDirectory) return
    if (privateDir.isDirectory) {
      if (privateDir.listFiles()?.isNotEmpty() == true) {
        // Conflict: the private entity wins; the public copy is kept aside for review.
        val backup = uniqueBackup(publicDir)
        if (!publicDir.renameTo(backup)) {
          throw java.io.IOException("failed to backup public dir " + publicDir.absolutePath)
        }
        Log.w(TAG, "private " + privateDir.absolutePath + " exists; public kept as " + backup.absolutePath)
        return
      }
      privateDir.deleteRecursively()
    }
    privateDir.parentFile?.mkdirs()
    copyTreeVerified(publicDir, privateDir)
    if (!publicDir.deleteRecursively()) {
      throw java.io.IOException("failed to delete public source " + publicDir.absolutePath)
    }
  }

  /** File-level reverse migration: drop the private symlink, copy the public file back, then delete the public source. */
  private fun reverseMigrateFile(privateFile: File, publicFile: File) {
    if (isSymlink(privateFile)) {
      Files.delete(privateFile.toPath())
    }
    if (!publicFile.isFile) return
    if (privateFile.exists()) {
      if (privateFile.length() > 0) {
        // The public file is the post-migration active copy (settings/profiles); the public one wins,
        // and the stale private entity is kept as a backup rather than silently deleted.
        val backup = uniquePrivateBackup(privateFile)
        if (!privateFile.renameTo(backup)) {
          throw java.io.IOException("failed to backup private file " + privateFile.absolutePath)
        }
        Log.w(TAG, "private file backed up as " + backup.absolutePath)
      } else {
        privateFile.delete()
      }
    }
    privateFile.parentFile?.mkdirs()
    publicFile.copyTo(privateFile, overwrite = true)
    if (privateFile.length() != publicFile.length()) {
      throw java.io.IOException("copy verification failed for " + publicFile.absolutePath)
    }
    if (!publicFile.delete()) {
      throw java.io.IOException("failed to delete public source " + publicFile.absolutePath)
    }
  }

  /** Ensure the public export repo exists: root dir + .nomedia + exports/. */
  private fun ensurePublicExportRepo(dshData: File) {
    try {
      dshData.mkdirs()
      File(dshData, ".nomedia").writeText("")
      File(dshData, "exports").mkdirs()
      // 0.13.1 W3/W4：目录布局说明（每次启动刷新，内容随版本演进）。
      File(dshData, "README.txt").writeText(
        "dsh-mobile 共享数据目录（Documents/dshdata）说明\n" +
          "================================================\n" +
          "本目录只存放导出物与日志，应用运行数据（配置/会话/凭据）在应用私有目录，\n" +
          "文件管理器不可见——在本目录改 settings.yaml 不会生效（引擎读不到）。\n\n" +
          "目录布局：\n" +
          "  exports/                 会话与配置的导出物\n" +
          "    config/settings.yaml   配置导出（设置 > 开发者选项 > 导出配置 生成）\n" +
          "                           修改本文件后点「导入配置」即可生效（无需重装）\n" +
          "  log/                     开发者调试日志（默认关，设置 > 开发者选项 开启）\n" +
          "  diagnostics/             启动失败/崩溃时自动生成的诊断包（engine.log + 环境信息 + logcat），\n" +
          "                           反馈 issue 时直接整目录打包上传即可\n\n" +
          "改配置的正确途径：设置界面各项开关；或 导出配置 -> 文件管理器编辑 -> 导入配置；\n" +
          "进阶：设置 > 开发者选项 > 打开控制台（快照内 bash，可直接 vi settings.yaml）。\n",
      )
    } catch (t: Throwable) {
      Log.w(TAG, "public export repo setup failed", t)
    }
  }

  private fun isSymlink(file: File): Boolean = Files.isSymbolicLink(file.toPath())

  private fun uniqueBackup(publicFile: File): File {
    var candidate = File(publicFile.parentFile, publicFile.name + ".public-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(publicFile.parentFile, publicFile.name + ".public-backup-" + i)
      i++
    }
    return candidate
  }

  private fun uniquePrivateBackup(privateFile: File): File {
    var candidate = File(privateFile.parentFile, privateFile.name + ".private-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(privateFile.parentFile, privateFile.name + ".private-backup-" + i)
      i++
    }
    return candidate
  }

  /** Recursively copy a directory tree, verifying the file count and total size. */
  private fun copyTreeVerified(src: File, dst: File) {
    dst.mkdirs()
    src.listFiles()?.forEach { f ->
      val target = File(dst, f.name)
      if (f.isDirectory) {
        copyTreeVerified(f, target)
      } else {
        f.copyTo(target, overwrite = true)
      }
    }
    val srcFiles = src.walkBottomUp().filter { it.isFile }.toList()
    val dstFiles = dst.walkBottomUp().filter { it.isFile }.toList()
    val srcSize = srcFiles.sumOf { it.length() }
    val dstSize = dstFiles.sumOf { it.length() }
    if (srcFiles.size != dstFiles.size || srcSize != dstSize) {
      throw java.io.IOException("copy verification failed for " + src.absolutePath)
    }
  }

  /**
   * Runtime patches: overlay fix files from assets/patched onto the corresponding snapshot
   * locations (idempotent). Overlayed fixes (all marked by a sentinel string in the target file,
   * so they are re-applied automatically after a snapshot refresh/re-extract):
   *  - primitives-index.js: clipboard fallback for WebViews where navigator.clipboard is denied
   *  - attachment-local-index.js: Android link(2) blocked by sepolicy → copyFile fallback + EACCES tolerance
   *  - web-frontend-index.html: immersive viewport-fit=cover patch
   *  - llm-deepseek: NOT patched — dsh 0.1.1-rc.2 bundles deepseek-v4-flash-vision-exp natively
   *    with the corrected image-request serialization (see applyRuntimePatches).
   *  - session-persistence-jsonl-index.js / fs-local-index.js: Android link(2) fallback — dsh
   *    0.1.1-rc.1 dropped the EACCES/EPERM/ENOTSUP → rename fallback that rc.8 shipped; Android
   *    app domains forbid link(2) (sepolicy), re-add it as a full-file overlay (as in rc.8).
   *  Patches use a content fingerprint (no fixed marker), so an updated asset re-applies on
   *  upgrade instead of being skipped by a stale marker string (the v1→v2 update bug).
   * (v0.12.4 rc8 removed the onImagePicked/llm-deepseek/textzoom patches — rc8's native image
   * request support and no-cache hardening supersede them.)
   */
  private fun applyRuntimePatches() {
    val dshPkgs = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai")
    val webDist = File(dshPkgs, "dsh-web-frontend/dist")
    val home = File(homeDir, ".dsh")
    // v0.12.4 (rc8) migration: onImagePicked/describeImage/bundle-hardening/textzoom patches
    // were removed — rc8's official native image request (serializeRequestWithImages) and no-cache
    // hardening cover them; the textzoom feature was dropped after the settings-general rework
    // (the bridge method is kept).
    applyAssetPatch("patched/primitives-index.js",
      File(dshPkgs, "dsh-client-ui-primitives/lib/index.js"))
    applyAssetPatch("patched/attachment-local-index.js",
      File(dshPkgs, "dsh-attachment-local/lib/index.js"))
    applyAssetPatch("patched/web-frontend-index.html",
      File(webDist, "index.html"), hashAdaptive = true)
    // dsh 0.1.1-rc.2 bundles deepseek-v4-flash-vision-exp natively (with the corrected
    // image-request serialization), so the old rc.1 catalog overlay is obsolete — the native
    // file is left untouched.
    applyAssetPatch("patched/session-persistence-jsonl-index.js",
      File(dshPkgs, "dsh-session-persistence-jsonl/lib/index.js"))
    applyAssetPatch("patched/fs-local-index.js",
      File(dshPkgs, "dsh-fs-local/lib/index.js"))
  }

  /** Overwrite-style patch: applies when the target differs from the bundled asset (content
   *  fingerprint), so an updated asset re-applies on upgrade instead of being skipped by a stale
   *  marker string (the v1→v2 asset-update failure).
   *  hashAdaptive（2026-08-23，前端审核 CRITICAL#4）：web-frontend-index.html 引用引擎 dist 的
   *  content-hashed bundle 名（/assets/index-<hash>.js）。引擎升级 → hash 变化 → patched 模板
   *  仍指向旧 hash → 404 白屏。开启后：先从引擎现存 index.html 提取当前 hash 引用，再替换
   *  patched 模板中的旧引用（asset 模板本身可长期不随引擎更新）。 */
  private fun applyAssetPatch(asset: String, target: File, hashAdaptive: Boolean = false) {
    // Patches track bundle layouts: when the runtime no longer ships the patched package
    // (e.g. dsh-client-ui-primitives dropped from the dependency graph in dsh 0.1.1-rc.1),
    // stop applying instead of littering a dead overlay into to the tree.
    if (!target.parentFile.exists()) {
      Log.i(TAG, "runtime patch skipped (target package absent): $asset")
      return
    }
    val assetBytes = try {
      context.assets.open(asset).use { it.readBytes() }
    } catch (e: Exception) {
      Log.w(TAG, "runtime patch asset missing: $asset")
      return
    }
    val finalBytes = if (hashAdaptive) adaptIndexHashes(assetBytes, target) else assetBytes
    if (target.exists() && target.readBytes().contentEquals(finalBytes)) return
    try {
      target.parentFile?.mkdirs()
      target.writeBytes(finalBytes)
      Log.i(TAG, "runtime patch applied/updated: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }

  /**
   * 把 patched index.html 中旧的 /assets/index-*.js、vendor-*.js|css 引用替换为
   * 引擎 dist/index.html 当前实际引用的新 hash。提取失败（引擎 index 读不到/无匹配）
   * 时原样返回——此时与旧行为一致，宁可不注入也不写坏。
   * 匹配规则：引擎当前引用 `assets/<stem>-<hash>.<ext>`，patched 中存在
   * `assets/<stem>-<hash'>.<ext>`（同 stem/同 ext，hash 不同）→ 替换为新 hash。
   */
  private fun adaptIndexHashes(patched: ByteArray, engineIndex: File): ByteArray {
    return try {
      val current = engineIndex.readText()
      val p = patched.toString(Charsets.UTF_8)
      var out = p
      // P1-A1（2026-10 专家审查修复）：hash 字符类补 _-——vite 产物哈希含下划线/连字符
      // （实机现值 vendor-D22_Mp1f.js / vendor-CjyC-hUb.css），旧字符类漏匹配 → 注入
      // patched/index.html 引用悬空旧 hash → 引擎升级后白屏/丢 CSS（坑 16 家族）。
      val refRe = Regex("(?:/|\")assets/([A-Za-z0-9_.-]+)-([A-Za-z0-9_-]{8})\\.(js|css)(?:\"| )")
      val curRefs = refRe.findAll(current)
      for (m in curRefs) {
        val stem = m.groupValues[1]
        val hash = m.groupValues[2]
        val ext = m.groupValues[3]
        val old = Regex("assets/" + Regex.escape(stem) + "-[A-Za-z0-9_-]{8}\\." + ext)
        out = out.replace(old, "assets/$stem-$hash.$ext")
      }
      out.toByteArray(Charsets.UTF_8)
    } catch (e: Exception) {
      Log.w(TAG, "index hash adaptation failed; keeping bundled patch: " + e.message)
      patched
    }
  }

  /** Append-style patch (for cordis.patch.yml, keeping the user's existing entries). */
  private fun applyAssetPatchAppend(asset: String, target: File, marker: String) {
    if (target.exists() && target.readText().contains(marker)) return
    try {
      val content = context.assets.open(asset).bufferedReader().use { it.readText() }
      target.parentFile?.mkdirs()
      val existing = if (target.exists()) target.readText() else ""
      val sep = if (existing.isNotBlank() && !existing.endsWith("\n")) "\n" else ""
      target.writeText(existing + sep + content)
      Log.i(TAG, "runtime patch appended: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }

  /** Start the dsh web engine from the embedded snapshot. */
  fun startEngine(port: Int = EngineProbe.ENGINE_PORT): Boolean {
    // LD_PRELOAD depends on the snapshot's termux-exec lib: when missing, every child exec fails,
    // and combined with the cooldown window that means a silent 90s engine outage — assert explicitly
    // before starting and fail loudly if absent.
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    if (!preload.exists()) {
      Log.e(TAG, "engine start failed: termux-exec preload missing at " + preload.absolutePath)
      return false
    }
    // Seagull fork：每次引擎启动前确保内置工具/Ubuntu rootfs 就位（幂等；hasAsset 守卫 + 覆盖写）。
    // 修复：先装无工具首包、后装带工具新包时快照指纹不变 → refreshSnapshot 不跑 → 工具装不上。
    extractToolAssets()
    val now = System.currentTimeMillis()
    // Process-level CAS: only one concurrent call really starts (device-measured EADDRINUSE double-start).
    if (!STARTING.compareAndSet(false, true)) return true
    // Cooldown window: no re-start within 90s of the last attempt (a cold boot takes 20-45s).
    // Review 2026-08-18 (L2 semantics): returning true here means "no further start needed"
    // (the engine is most likely already starting), not "this call started it successfully" — callers
    // poll engine reachability themselves, so this never causes a wrong wait, but it must not be
    // read as proof of success.
    // 2026-08-23 修复（审核 CRITICAL#1，用户实测"重试不 kill 旧引擎进程"）：冷却窗内若引擎
    // 实际不可达（探活 down），冷却窗不应阻止重试——旧实现让挂死进程占着引擎端口直到 EADDRINUSE。
    // 同时 startEngine 前必须先终结残留进程：destroy() 仅 SIGTERM，引擎挂死时需 destroyForcibly。
    val withinCooldown = now - EngineManager.lastStartAttemptAt < START_COOLDOWN_MS
    if (withinCooldown) {
      val engineReachable = try { EngineProbe.check(300).optBoolean("running", false) } catch (_: Exception) { false }
      if (engineReachable) {
        STARTING.set(false)
        LogCollector.log(TAG, "engine start skipped (cooldown window; engine reachable)")
        return true
      }
      // 冷启动保护（2026-10 循环重启修复）：引擎进程活着 = 正在冷启动（20-45s 内探活
      // 必然失败属正常）——本窗口内绝不 kill 重启。旧实现在冷却窗内只要探活不可达就
      // 「绕过冷却窗」直接 killExistingEngine，把 5s 前刚 spawn 的引擎掐灭，看门狗下
      // 一 tick 再来一遍 → 引擎永远无法完成冷启动（用户实测「用久了老是重启卡死」主根因）。
      if (engineProcessAlive()) {
        STARTING.set(false)
        LogCollector.log(TAG, "engine start skipped (cold boot in progress; process alive)")
        return true
      }
      // 进程已死（启动即崩）：崩溃循环限速，避免每 5s 一次的 kill-restart 风暴。
      if (now - EngineManager.lastStartAttemptAt < CRASH_RETRY_MIN_MS) {
        STARTING.set(false)
        LogCollector.log(TAG, "engine start skipped (crash retry throttle)")
        return true
      }
      LogCollector.log(TAG, "engine start: cooldown bypassed (engine process dead " + (now - EngineManager.lastStartAttemptAt) + "ms after last start)")
    }
    return try {
      // 旧进程清理：无论句柄是否还在，先终结残留（引擎挂死/内存里 fork 掉的孤儿）。
      killExistingEngine()
      // 0.13.1 W5：坏键迁移必须在引擎读 settings 前完成。
      repairSettingsSeed()
      // 0.13.1 W3/W4：共享目录 README 每次启动刷新（此前只在迁移路径调用，正常启动不落盘）。
      ensurePublicExportRepo(dshDataDir)
      applyRuntimePatches()
      // --no-open: the engine must never try to open a desktop browser on Android
      // (the WebView IS the UI). Without it, rc.2's spawn xdg-open on a missing
      // binary stalls engine serve on some emulators (MuMu root observed);
      // the flag is the official engine CLI switch (see bin.js docs).
      val args = arrayOf(
        nodeBin.absolutePath, "--expose-internals", dshBin.absolutePath, "web", "--port", port.toString(), "--no-open",
      )
      EngineManager.engineProcess = startWithArgs(args, shellEnv())
      // The cooldown is written only after a real start: failure paths don't consume the window (retry is immediate).
      EngineManager.lastStartAttemptAt = now
      LogCollector.log(TAG, "engine started")
      true
    } catch (t: Throwable) {
      Log.e(TAG, "engine start failed", t)
      LogCollector.log(TAG, "engine start FAILED: " + (t.message ?: t.javaClass.simpleName))
      // 0.13.1 W3：失败现场镜像到共享目录（此前 engine.log 只在私有域，外界拿不到）。
      mirrorDiagnosticsToShared("engine-spawn-failed")
      false
    } finally {
      STARTING.set(false)
    }
  }

  /**
   * Spawn the engine, falling back to the system linker when the direct exec
   * is denied: Android 15+ apps targeting SDK 35+ may not exec app-data ELF
   * binaries, but loading them through /system/bin/linker64 is the same
   * mechanism as native libraries (always permitted for app data).
   */
  private fun startWithArgs(args: Array<String>, env: Map<String, String>): Process {
    val log = File(context.filesDir, "engine.log")
    rotateEngineLog(log)
    fun build(argv: List<String>): ProcessBuilder =
      ProcessBuilder(argv).also { b ->
        b.environment().putAll(env)
        b.redirectErrorStream(true)
        b.redirectOutput(log)
      }
    return try {
      build(args.toList()).start()
    } catch (e: java.io.IOException) {
      if (e.message?.contains("Permission denied") != true) throw e
      Log.w(TAG, "direct exec denied, falling back to linker64: " + e.message)
      build(listOf("/system/bin/linker64") + args.toList()).start()
    }
  }

  /**
   * 0.13.1 W3：engine.log 世代轮转（保留 3 代）——redirectOutput 语义是每次启动截断，
   * 看门狗 5s 循环重启时崩溃现场每次被清掉，用户永远只剩最后一次的输出。
   */
  private fun rotateEngineLog(log: File) {
    try {
      val prev1 = File(log.parentFile, "engine.log.1")
      val prev2 = File(log.parentFile, "engine.log.2")
      if (prev2.exists()) prev2.delete()
      if (prev1.exists()) prev1.renameTo(prev2)
      if (log.exists()) log.renameTo(prev1)
    } catch (t: Throwable) {
      Log.w(TAG, "engine.log rotation failed", t)
    }
  }

  /** 0.13.1 W3：最近一次死亡的引擎进程退出码（进程活着或句柄丢失时返回 null）。 */
  fun engineExitInfo(): String? {
    val held = EngineManager.engineProcess ?: return null
    if (held.isAlive) return null
    return try {
      "exit=" + held.exitValue()
    } catch (_: Throwable) {
      null
    }
  }

  /**
   * 0.13.1 W3：失败诊断镜像（best-effort，绝不抛出）。把 engine.log 全世代 + 退出码 +
   * 环境/设备信息 + 最近 logcat 写入共享目录 Documents/dshdata/diagnostics/<时间戳>-<原因>/，
   * 用户用文件管理器即可直接复制去反馈（此前全在私有目录，失败时外界拿不到任何现场）。
   * 触发点：spawn 失败 / 进程死亡 / 健康检查超时 / 快照解压失败 / UndoGate 急救。
   */
  fun mirrorDiagnosticsToShared(reason: String) {
    // 节流（2026-10）：spawn 失败路径会被看门狗每 tick 触发，旧实现每 5s 落一个诊断包
    // （logcat 400 行/次）→ diagnostics 目录无限膨胀。60s 内只镜像一次。
    val now = System.currentTimeMillis()
    if (now - EngineManager.lastDiagnosticsMirrorAt < DIAGNOSTICS_MIRROR_MIN_INTERVAL_MS) {
      LogCollector.log(TAG, "diagnostics mirror throttled (" + reason + ")")
      return
    }
    EngineManager.lastDiagnosticsMirrorAt = now
    try {
      val ts = java.text.SimpleDateFormat("yyyyMMdd-HHmmss", java.util.Locale.US).format(java.util.Date())
      val dir = File(File(dshDataDir, "diagnostics"), ts + "-" + reason)
      if (!dir.mkdirs() && !dir.isDirectory) return
      val log = File(context.filesDir, "engine.log")
      for (f in arrayOf(log, File(log.parentFile, "engine.log.1"), File(log.parentFile, "engine.log.2"))) {
        try {
          if (f.exists()) f.copyTo(File(dir, f.name), overwrite = true)
        } catch (_: Throwable) {
        }
      }
      try {
        File(dir, "info.txt").writeText(buildDiagnosticsText(reason))
      } catch (_: Throwable) {
      }
      try {
        val p = ProcessBuilder("logcat", "-d", "-v", "threadtime", "-t", "400").redirectErrorStream(true).start()
        val out = p.inputStream.readBytes()
        if (out.isNotEmpty()) File(dir, "logcat-recent.txt").writeBytes(out)
      } catch (_: Throwable) {
      }
      LogCollector.log(TAG, "diagnostics mirrored: " + dir.absolutePath)
    } catch (t: Throwable) {
      Log.w(TAG, "diagnostics mirror failed", t)
    }
  }

  private fun buildDiagnosticsText(reason: String): String {
    val sb = StringBuilder()
    sb.append("reason: ").append(reason).append('\n')
    sb.append("time: ").append(java.util.Date().toString()).append('\n')
    try {
      sb.append("app: ").append(BuildConfig.VERSION_NAME).append(" (versionCode ").append(BuildConfig.VERSION_CODE).append(")\n")
    } catch (_: Throwable) {
    }
    sb.append("device: ").append(android.os.Build.MANUFACTURER).append(' ').append(android.os.Build.MODEL)
      .append(" / Android ").append(android.os.Build.VERSION.SDK_INT).append('\n')
    sb.append("abi: ").append(android.os.Build.SUPPORTED_ABIS.joinToString(",")).append('\n')
    engineExitInfo()?.let { sb.append("engine_exit: ").append(it).append('\n') }
    try {
      val probe = EngineProbe.check(500)
      sb.append("probe: ").append(probe.toString()).append('\n')
    } catch (_: Throwable) {
    }
    return sb.toString()
  }

  /**
   * 0.13.1 W5：settings.yaml 坏键迁移。0.13.0 出厂 seed 的 `llm-deepseek:` 裸键（YAML null）
   * 会被首启持久化；fx-1 只修了 APK 内出厂模板，覆盖安装升级的设备上存量坏配置仍在——
   * 引擎 settings section() 抛 TypeError 且被插件加载器吞掉（engine.log 零痕迹），表现为
   * 模型页提供方列表空白 + 「添加提供方」点击无响应（2026-08-28 模拟器双向复现实锤）。
   * 启动前把已知坏裸键修复为空对象；幂等、只触碰已知键、失败不阻塞启动。
   * 判定必须带前瞻：裸键后紧跟缩进子键 = 合法映射（非 null），绝不能改——否则插入重复键
   * DUPLICATE_KEY 直接炸引擎（2026-08-28 首版修复在 fx-1 正常文件上翻车实录）。
   */
  private fun repairSettingsSeed() {
    try {
      val f = File(File(homeDir, ".dsh"), "settings.yaml")
      if (!f.exists()) return
      val src = f.readText()
      val lines = src.split("\n")
      val out = StringBuilder(src.length + 32)
      var changed = false
      for (i in lines.indices) {
        val line = lines[i]
        val m = Regex("^(llm-deepseek|llm-pi-ai):([ \t]*(#.*)?)$").find(line)
        if (m == null) {
          out.append(line).append('\n')
          continue
        }
        // 前瞻下一个非空行：缩进子键 = 合法映射（非 null），跳过不改。
        // 注意：缩进的【注释行】不构成子键（YAML 注释不参与结构）——fx-1 升级真机的存量
        // 坏 seed 正是「裸键 + 缩进注释」形态（2026-08-29 真机活体实锤），必须穿透注释继续判定。
        val next = lines.drop(i + 1)
          .firstOrNull { it.isNotBlank() && !it.trimStart().startsWith("#") }
        if (next != null && (next.startsWith(" ") || next.startsWith("\t"))) {
          out.append(line).append('\n')
          continue
        }
        when (m.groupValues[1]) {
          "llm-deepseek" -> out.append("llm-deepseek: {}")
          else -> out.append("llm-pi-ai:\n  providers: {}")
        }
        changed = true
        // 保留原行尾注释（如有）。
        val comment = m.groupValues[2]
        if (comment.isNotBlank()) out.append(' ').append(comment.trimStart())
        out.append('\n')
      }
      val fixed = out.toString().removeSuffix("\n")
      if (changed && fixed != src) {
        f.writeText(fixed)
        LogCollector.log(TAG, "settings.yaml repaired: bare null key -> object (0.13.0 seed migration)")
      }
    } catch (t: Throwable) {
      Log.w(TAG, "settings.yaml repair failed (non-fatal)", t)
    }
  }

  /** Stop the engine process (best-effort). 仅由用户显式关闭路径调用（shutdownToGuide），
   *  Activity/服务生命周期销毁不得调用——引擎保活归 EngineService。 */
  fun stopEngine() {
    val held = EngineManager.engineProcess
    if (held != null) {
      try {
        held.destroy()
        // SIGTERM 后 node 可能要几秒才退出；不等待直接返回会让调用方误以为已停
        // （shutdownToGuide 随后 stopService 才彻底）。有界等待 + 强杀兜底。
        if (!held.waitFor(3, java.util.concurrent.TimeUnit.SECONDS)) {
          held.destroyForcibly()
          held.waitFor(2, java.util.concurrent.TimeUnit.SECONDS)
        }
      } catch (_: Throwable) {
      }
    }
    EngineManager.engineProcess = null
    // 进程句柄之外的孤儿（watchdog fork 的）也要收，与 killExistingEngine 兜底同口径。
    killOrphanEngineProcesses()
    LogCollector.log(TAG, "engine stopped (manual)")
    // Reset the cooldown after a manual stop: returning to the foreground should allow an immediate restart.
    EngineManager.lastStartAttemptAt = 0
  }

  /**
   * 引擎进程存活判定（0.13.0 启动超时 D1 的事实源）：进程句柄活着，或引擎端口已可达，
   * 即视为「引擎还在」（冷启动 20-45s 中轮询窗口内不许宣判失败）。两者皆否才返回 false。
   * 供 startEngineFlow 的超时语义使用——进程活着就继续等，只有进程死才触发回退。
   */
  fun engineProcessAlive(): Boolean {
    val held = EngineManager.engineProcess
    if (held != null && held.isAlive) return true
    if (held == null) {
      // 句柄丢失（看门狗曾被 fork 或孤儿）：以端口可达性兜底判定。
      return try { EngineProbe.check(300).optBoolean("running", false) } catch (_: Exception) { false }
    }
    return false
  }

  /**
   * 终结残留引擎进程：先杀持有句柄的（destroyForcibly + waitFor 有界等待），
   * 再兜底 pkill 快照 node 进程（处理服务/看门狗曾被 fork、句柄已被覆盖的孤儿）。
   * 幂等：无残留时零动作。绝不等待超过 5s（不阻塞启动路径）。
   */
  private fun killExistingEngine() {
    val held = EngineManager.engineProcess
    if (held != null) {
      try {
        held.destroy()
        if (!held.waitFor(3, java.util.concurrent.TimeUnit.SECONDS)) {
          held.destroyForcibly()
          held.waitFor(2, java.util.concurrent.TimeUnit.SECONDS)
        }
      } catch (_: Throwable) {
      }
      EngineManager.engineProcess = null
    }
    killOrphanEngineProcesses()
  }


  /** Reset the 90s cooldown window: auto-undo (config rollback) or user retry
   *  must be allowed to start the engine immediately. Manual stop already does this. */
  fun resetCooldown() {
    EngineManager.lastStartAttemptAt = 0
  }

  /**
   * Update-manager-v2 probe state machine (PRD F3.2/F1.10): after an online
   * snapshot swap, `usr-old` is kept and `.update-pending` is set. Each engine
   * probe result feeds this: N consecutive healthy ticks finalize (delete the
   * old runtime); a pending window that never turns healthy rolls back to the
   * previous runtime (second-layer fallback; the F3 plugin layer stays in
   * charge of config/plugin-code rollbacks). Never throws.
   */
  fun onEngineProbe(healthy: Boolean) {
    val pending = File(context.filesDir, ".update-pending")
    if (!pending.exists()) {
      updateHealthTicks = 0
      return
    }
    if (healthy) {
      updateHealthTicks++
      if (updateHealthTicks >= UPDATE_CONFIRM_TICKS) {
        pending.delete()
        File(context.filesDir, ".update-pending-at").delete()
        File(context.filesDir, "usr-old").deleteRecursively()
        updateHealthTicks = 0
        LogCollector.log(TAG, "update confirmed: old runtime cleaned (usr-old removed)")
      }
    } else {
      updateHealthTicks = 0
      val at = File(context.filesDir, ".update-pending-at").takeIf { it.exists() }?.readText()?.trim()?.toLongOrNull()
      if (at != null && System.currentTimeMillis() - at > UPDATE_ROLLBACK_MS) {
        rollbackToOld()
        pending.delete()
        File(context.filesDir, ".update-pending-at").delete()
      }
    }
  }

  /** Swap the current runtime back to the kept previous one; restarts the engine from it. */
  private fun rollbackToOld() {
    val usr = File(context.filesDir, "usr")
    val old = File(context.filesDir, "usr-old")
    if (!old.exists()) return
    try {
      val broken = File(context.filesDir, "usr-broken")
      broken.deleteRecursively()
      if (usr.exists()) usr.renameTo(broken)
      if (old.renameTo(usr)) {
        LogCollector.log(TAG, "update rolled back to previous runtime; restarting engine")
        EngineManager.lastStartAttemptAt = 0 // allow an immediate restart (no cooldown stall)
        try { startEngine() } catch (_: Throwable) {
        }
      } else {
        // Rollback of the rollback: the failed old-swap left no usr — put the broken new one back.
        if (!usr.exists() && broken.exists()) broken.renameTo(usr)
        Log.e(TAG, "update rollback failed; usr restored from usr-old: " + usr.exists())
      }
    } catch (t: Throwable) {
      Log.e(TAG, "update rollback threw", t)
    }
  }

  /**
   * Snapshot environment shared by engine/console/log processes (PATH/LD_LIBRARY_PATH/HOME/DSH_HOME/
   * TERMUX_* injected explicitly — the snapshot is self-sufficient, no Termux app needed). Idempotent:
   * safe to call repeatedly (ensurePrivateDshData and the TMPDIR mkdirs are both idempotent).
   */
  fun shellEnv(): Map<String, String> {
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    // Cert paths hardcoded at Termux package build time (/data/data/com.termux/...) break after the
    // PREFIX relocation; relocate-snapshot.py doesn't rewrite ELF, so env vars cover the functional
    // paths — curl/wget/git https CA validation depends on them (v0.12.3-FX-2).
    val cert = File(usrDir, "etc/tls/cert.pem").takeIf { it.exists() }
    val certEnv = if (cert != null) {
      mapOf(
        "SSL_CERT_FILE" to cert.absolutePath,
        "CURL_CA_BUNDLE" to cert.absolutePath,
        "GIT_SSL_CAINFO" to cert.absolutePath,
        // 快照 node 编译期硬编码 OpenSSL 配置路径 /data/data/com.termux/...（app 域不可读）：
        // 不注入则任何 node/npm 子进程启动即 OpenSSL configuration error 退出（agent 工具调用
        // npm/node 全部失败，引擎本体侥幸存活）。与 UndoGate/AdbState 同一修复（坑 #5 统一到
        // 引擎级 env，覆盖 agent 所有工具子进程，2026-08-24 真机实测实锤）。
        "OPENSSL_CONF" to File(usrDir, "etc/tls/openssl.cnf").absolutePath,
      )
    } else emptyMap()
    return mapOf(
      "PATH" to (usrDir.absolutePath + "/bin:/system/bin"),
      "LD_LIBRARY_PATH" to (usrDir.absolutePath + "/lib"),
      "HOME" to homeDir.absolutePath,
      // DSH_HOME always stays in the private domain (FUSE forbids symlinks, so the public domain
      // can't maintain the profiles/node_modules flat fallback); all runtime user data lives in private
      // files/home/.dsh, and public Documents/dshdata is only the export repo.
      "DSH_HOME" to ensurePrivateDshData().absolutePath,
      // os.tmpdir() falls back to the baked-in Termux tmp on Android
      // (unwritable from the app domain); keep spill inside filesDir.
      "TMPDIR" to File(homeDir, "tmp").apply { mkdirs() }.absolutePath,
      // Android 16 forbids exec of app-data ELF regardless of targetSdk
      // (observed on Android 16/vivo: direct exec EACCES even at targetSdk
      // 34). Termux's execve hook re-routes denied execs through
      // /system/bin/linker64 (same mechanism as JNI libs); the snapshot
      // ships libtermux-exec-*-ld-preload.so. The hook only rewrites for
      // untrusted_app_25/27 SELinux domains, so force mode is required.
      "LD_PRELOAD" to preload.absolutePath,
      "TERMUX_EXEC__SYSTEM_LINKER_EXEC__MODE" to "force",
      "TERMUX_EXEC__EXECVE_CALL__INTERCEPT" to "1",
      "TERMUX__ROOTFS" to usrDir.parentFile.absolutePath,
      "TERMUX__PREFIX" to usrDir.absolutePath,
      "TERMUX_APP__DATA_DIR" to context.filesDir.parentFile.absolutePath,
      "TERMUX_APP__LEGACY_DATA_DIR" to "/data/data/com.dsharnessmobile.shell",
      "TERMUX_VERSION" to BuildConfig.TERMUX_VERSION,
      // Directory-picker endpoint auth token (validated by the web-compat plugin via x-dsh-pick-token).
      "DSH_PICK_TOKEN" to (pickToken ?: ""),
      // ADB 授权状态（0.13.0 F1.7）：dsh-android-bridge 插件据此失败关闭；门控=完全访问档位+开关+配对。
      "DSH_ADB_ALLOW" to (if (AdbState.allowSwitch(context)) "1" else "0"),
      "DSH_ADB_PAIRED" to (if (AdbState.paired(context)) "1" else "0"),
      "DSH_ADB_WIRELESS" to (if (AdbState.paired(context)) "1" else "0"),
      // 门1「完全访问档位」= All Files Access（系统权限）——引擎侧判定与壳侧 AdbState.fullAccess() 同源
      // （审校 C6 语义分裂修复：此前引擎把「写面档位」误当门1，见 review 文档）；授予后重启引擎生效。
      "DSH_ADB_FULLACCESS" to (if (AdbState.fullAccess()) "1" else "0"),
      // Vision backend (Qwen-VL) API key: read from a private file rather than hardcoded in source.
      "DASHSCOPE_API_KEY" to (File(context.filesDir, "dashscope-key.txt").takeIf { it.exists() }?.readText()?.trim() ?: ""),
      // DeepSeek 官方 provider（dsh-llm-deepseek，provider=deepseek-official）：同模式私有文件注入。
      "DEEPSEEK_API_KEY" to (File(context.filesDir, "deepseek-key.txt").takeIf { it.exists() }?.readText()?.trim() ?: ""),
      // node 预热（0.13.0 启动提速 D3）：v8 模块编译缓存——引擎/工具子进程首启自动生成、
      // 二次冷启动命中，直接缩短 node 冷启 require 树编译时间（K20 Pro 实测每次冷启都慢、
      // 0.13.0 之前全快；缓存目录持久在 home/.dsh 下，随用户数据保留不随快照）。
      "NODE_COMPILE_CACHE" to File(ensurePrivateDshData(), ".node-compile-cache").apply { mkdirs() }.absolutePath,
    ) + certEnv
  }

  companion object {
    private const val TAG = "dsh-engine"

    /** 工具资产解压并发锁（MainActivity/EngineService 双实例可能并发 startEngine）。 */
    private val TOOL_EXTRACT_LOCK = Any()

    /** Healthy ticks (each 5s watchdog poll) required before the update-v2 finalize deletes usr-old. */
    const val UPDATE_CONFIRM_TICKS = 3

    /** Pending window before an unhealthy runtime is rolled back (PRD F3: recovery ≤ 3 min). */
    const val UPDATE_ROLLBACK_MS = 180_000L

    /** Watchdog/retry backoff: no new start within this window of the last
     *  attempt. Cold node boot on the phone takes 20-45s (plugin tree + first
     *  bind); a 5s watchdog poll would otherwise race a healthy boot and
     *  double-start the engine (device-observed EADDRINUSE). 90s covers the
     *  slowest observed boot with margin. */
    const val START_COOLDOWN_MS = 90_000L

    /** 崩溃重启限速（2026-10 循环重启修复）：上次启动的进程已死（启动即崩）时，
     *  距上次启动不足该间隔不重复重启——避免「spawn→秒崩→5s 后再 spawn」风暴。 */
    const val CRASH_RETRY_MIN_MS = 20_000L

    /** 诊断镜像最小间隔（2026-10）：spawn 失败路径每 tick 触发时限制落盘频率，
     *  防止 diagnostics 目录每 5s 膨胀一个包（logcat 400 行/次）。 */
    const val DIAGNOSTICS_MIRROR_MIN_INTERVAL_MS = 60_000L

    /** 上次诊断镜像时间（节流基线）。 */
    @Volatile
    var lastDiagnosticsMirrorAt: Long = 0

    /** Process-level start CAS: visible across EngineManager instances (double-start race guard). */
    val STARTING = java.util.concurrent.atomic.AtomicBoolean(false)

    /**
     * 引擎进程句柄（2026-10 复盘修复）：进程级共享而非实例字段。MainActivity 与
     * EngineService 各自 new EngineManager，旧实现句柄是实例字段——服务侧看门狗的
     * engineProcessAlive() 永远拿不到 Activity 侧 spawn 的引擎（返回 null 只查端口），
     * 冷启动 20-45s 端口未监听期间误判「进程已死」→ 绕过冷却窗 kill 重启，且把正常
     * 冷启动判失败触发 UndoGate 自动回退。共享后所有实例对「引擎活着」事实一致。
     */
    @Volatile
    var engineProcess: Process? = null

    /** Last real start time (epoch ms); the watchdog cooldown-window baseline. */
    @Volatile
    var lastStartAttemptAt: Long = 0

    /**
     * Process-level shared directory-picker auth token (C1 fix, 2026-08-16):
     * generated once, then reused by every EngineManager instance in the process — MainActivity
     * rebuilds and EngineService watchdog engine restarts never lose/rotate the token, so auth stays
     * consistent even after the engine-side fail-closed (empty token → reject) path.
     */
    @Volatile
    var sharedPickToken: String? = null

    /** Get (or generate on first call) the process-level pick token. */
    fun ensurePickToken(): String {
      sharedPickToken?.let { return it }
      val token = java.util.UUID.randomUUID().toString()
      sharedPickToken = token
      return token
    }
    /**
     * 兜底终结无句柄的引擎孤儿（2026-10 stopEngine 复用提取）：pkill -f bin.js 不可靠
     * （vivo 对 linker64 包装进程实测不生效，坑 31），再扫 /proc/<pid>/cmdline 匹配
     * bin.js 特征 kill -9（排除自身 pid；pnpm/脚本子进程不含 bin.js 特征不会误杀）。
     */
    fun killOrphanEngineProcesses() {
      try {
        Runtime.getRuntime().exec(arrayOf("/system/bin/pkill", "-f", "bin.js")).waitFor()
      } catch (_: Throwable) {
      }
      try {
        val myPid = android.os.Process.myPid()
        File("/proc").listFiles()?.forEach { p ->
          val pid = p.name.toIntOrNull() ?: return@forEach
          if (pid == myPid) return@forEach
          val cmd = try { File(p, "cmdline").readBytes().toString(Charsets.UTF_8) } catch (_: Throwable) { "" }
          if (cmd.contains("bin.js")) {
            try { Runtime.getRuntime().exec(arrayOf("/system/bin/kill", "-9", pid.toString())).waitFor() } catch (_: Throwable) {}
          }
        }
      } catch (_: Throwable) {
      }
    }

  }
}
